spring.application.name=gymCRM-system

storage.data.file=classpath:data/initial-data.txt

spring.datasource.url=jdbc:postgresql://localhost:5432/gym_crm
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true